package com.artelier.api.dto.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.*;
import lombok.Data;

import java.util.List;

@Data
@Schema(
        name = "PaymentWebhookRequest",
        description = "Webhook payload received from Wompi when a transaction status changes"
)
public class PaymentWebhookRequest {

    @Schema(
            description = "Event type triggered by Wompi",
            example = "transaction.updated"
    )
    private String event;

    @Schema(
            description = "Transaction payload wrapper containing payment details"
    )
    private TransactionData data;

    @Schema(
            description = "Signature information used to validate webhook authenticity"
    )
    private SignatureData signature;

    @Schema(
            description = "Unix timestamp of the event (milliseconds)",
            example = "1715000000000"
    )
    private Long timestamp;

    @Data
    @Schema(description = "Wrapper for transaction object")
    public static class TransactionData {

        @Schema(description = "Transaction details from Wompi")
        private Transaction transaction;
    }

    @Data
    @Schema(description = "Wompi transaction data")
    public static class Transaction {

        @Schema(
                description = "Unique transaction ID generated by Wompi",
                example = "1234567890"
        )
        private String id;

        @Schema(
                description = "Reference sent by merchant to identify order",
                example = "ORDER-12345"
        )
        private String reference;

        @Schema(
                description = "Payment status returned by Wompi",
                example = "APPROVED"
        )
        private String status;

        @Schema(
                description = "Payment method used by customer",
                example = "NEQUI",
                allowableValues = {"NEQUI", "PSE", "CARD"}
        )
        @JsonProperty("payment_method_type")
        private String paymentMethodType;

        @Schema(
                description = "Amount in cents (e.g. 100000 = 1000.00 COP)",
                example = "100000"
        )
        @JsonProperty("amount_in_cents")
        private Long amountInCents;
    }

    @Data
    @Schema(description = "Signature block used to verify webhook integrity (HMAC)")
    public static class SignatureData {

        @Schema(
                description = "Checksum generated by Wompi to validate request authenticity",
                example = "a3f5c9d8e1b2..."
        )
        private String checksum;

        @Schema(
                description = "List of properties used to generate signature",
                example = "[\"transaction.id\", \"transaction.status\"]"
        )
        private List<String> properties;
    }
}